// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk2chfeefy2K9vtve9vgENPq_hsJMZhpo',
    appId: '1:415239482481:web:6394252c344487a1303fd0',
    messagingSenderId: '415239482481',
    projectId: 'ecommerceapp-fe8e3',
    authDomain: 'ecommerceapp-fe8e3.firebaseapp.com',
    storageBucket: 'ecommerceapp-fe8e3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXU0VLlzapFdgiUEZGO89U0Gb0IDu7BIQ',
    appId: '1:415239482481:android:7cf88bb3aa330b96303fd0',
    messagingSenderId: '415239482481',
    projectId: 'ecommerceapp-fe8e3',
    storageBucket: 'ecommerceapp-fe8e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeQ0mjotNuleZ5IsPP4EFDpgQRHuZ-TME',
    appId: '1:415239482481:ios:53863411c575b84c303fd0',
    messagingSenderId: '415239482481',
    projectId: 'ecommerceapp-fe8e3',
    storageBucket: 'ecommerceapp-fe8e3.appspot.com',
    androidClientId: '415239482481-8jfa36cappj46qc8nlufv66vj8nau2ol.apps.googleusercontent.com',
    iosClientId: '415239482481-rdccqunkem9ihee896q93ieiashec6f0.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );

}